sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test:lib
- npm run build:lib
before_deploy:
- cp README.md dist/@ngx-patterns/store-service/README.md
- cd dist/@ngx-patterns/store-service
deploy:
  provider: npm
  email: github@joost.io
  skip_cleanup: true
  api_key:
    secure: lGQ0DeXZOk0+cQfl4B+VLjrTKU6uxvxcE3kJxZgkP7sswr9g23aic6VUYR2OCTPSgkBU8w+puibw3VWNHyVKCHAVoWjuEWKttXtIOzqPyZnf2VU46I4q8WO8FJN6vS334Oum+Myxeb8uwrx9i4NJs3GjXIAKAkMjGsdtbFWeOMXhqbJXO1v6v3bG07y9eji0d1Db2gpK33mY15AtyOpG0XGv+T6qC5JgvzS2o6ww+PZHKkmpDPWYZOhWt7sa9ZXxbAn8I+uTIvXQzEzzEAvoUHMxynrgUKYw8UBOgYlXSV2wn/5yWGZsFI27SDENP75kgyx04b2JnzzN/TsUovHAHQMqUxCgO/foS9b0v0zWjYJAG2Fm0FOU0h0KNiJBQ1X8NDBNUTsmqwB691qdx0EX1SojKGv5Hfa79HNbH0DQQ5VTbaV+W6Acw/QKzWS+2EQNhZf8ktRozp92dZNtrB0GC80n9MebJDQmmRATGJefYV+QgVzrJbODBkCgTPrIz9QiPgrPaDBJLtCaij/fj+UOoRgisAEL0IrkhndesgiH3YbhSIrS19MFYZjbSWfoSo22tSLGEiPNa7Wz0ORTWCNWtoeAxFtHflvwHDoEP1QuZY3lIFIq/b/+9Z2fRb5i/rndp5TL0X8kdqc3TTmXTw1X7FMrtWFEB+xRjqUwwEEnH/8=
  on:
    tags: true
    repo: ngx-patterns/store-service
