sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test:lib
- npm run build:lib
before_deploy:
- cp README.md dist/@ngx-patterns/store-service/README.md
- cd dist/@ngx-patterns/store-service
deploy:
  provider: npm
  email: github@joost.io
  skip_cleanup: true
  api_key:
    secure: RagUZrLro0vg/GaulCJIgoGxI6ul/VYv3Ak31H2R2Q57OnsyOkT92BYoF25toFLJ95rfEoGzFa44+WCLrx7w/EiYbv4DW0hQKtq7wzpAGJzIEq648Gv6xFb46529ApMPOChtNJ9dCUPpEhFa6PWF10gJkYeiioccPDaRFScAA/kcA1euEDUho6MPCYBH5TEdXa8lESeq/iL4nB0vSLnoqdYsjTK7FUSrwbtAet0/5BFiRTQNI/PzfnZGz8U1mBa3ugQhh1G1vIZKyP/ozQVtKFyL2gW4Jh7s7B1690OaRCNSBV7QSdfXQPWmgOrmAUVFJY0K4FIkmisV11QFiyi/D/c1qwMnp1VAgyV4RCeL0chHISd6eyyO7Gtg+xe6cJwQ44HMT1WvimGsGCBqx/dN5Iu/FtDw5VNlgffALjg5nNobzd+Vi4AF3PrRpjm+NqhHJCoUFcdMAoUS8UNexVe0T2A2j1BBe3FmLxYBmidVcpLSRb6um/zkHnbv/3PsHhr2IBJ6DqqrKq/UeeTxun08GjQTBqkr06r2IwYuCGmFivxRwMD/U7W11RCCwNjNDomfK/+gcBUq3cmeGgHUl3orDyaQ5tER/MoD2Z4BOuGcGgCYVqgeIdPGI7lZZBS3hqWq4v1CTipS/U65WhXF9MfqhG5YwdcZ3PRxvQiD6/OGm5g=
  on:
    branch: master
    tags: true
    repo: ngx-patterns/store-service
